### ISSUE TITLE
Setting pin 13 to output in x12

### ISSUE THREAD

**Issue by AlessandroEmm** [clearwater/SwitecX25#23]
Hey there

Is there a particular reason this is 
https://github.com/clearwater/SwitecX25/blob/67ace428cedab342c1bcb1024f4ad0884cf0ccb0/SwitecX12.cpp#L38
in? 

I'm surprised none has mentioned it before. :-)

Thanks,
Alessandro

**Comment by guyc** [comment]
Hah, that's funny.  I looked back at the original experimental code this was derived from at https://guy.carpenter.id.au/gaugette/2017/04/29/switecx25-quad-driver-tests/ and it looks like I had an LED on pin 13 showing the drive direction.  It should not be there in the library.  I'll fix that.

**Comment by guyc** [comment]
Line removed.  Thanks Alessandro.
