### ISSUE TITLE
.zero() does not seem to "reset" the motor on X27s

### ISSUE THREAD

**Issue by timkettering** [clearwater/SwitecX25#4]
Ive been experimenting with your library and a X27 motor.  And it seems like the results of zero() are unpredictable.  The motor can come to a "zero" at various places.  I have looked at the code for zero() and it just seems to unwind all existing steps, but I dont see how it determines whether the motor has actually run into the mechanical stop.

I'm hoping you can give some clarification how this should work.  Cheers!

**Comment by SamFisher015** [comment]
Hello! I am using your library SwitecX25 to control stepper motors from a car cluster. (**Thank you very much for your work**!).

The photos below are the motors that I use. Your library is great for controlling them (I slightly adjusted the acceleration table and everything worked perfectly), although they are internally different from the usual X25 (X27) motors.

![Общий собранный вид](https://github.com/user-attachments/assets/e8d77b41-7c65-4c89-a7cb-9375893a70d7)
![Общий разобранный](https://github.com/user-attachments/assets/ceb82244-9636-4fb0-b4ce-0637830e0fa3)

 I have read everything that is written in this thread. But I am sure that it is possible to somehow determine mechanical zero (without additional sensors) or at least determine whether the motor is rotating or has already reached the stop.

Please watch this videos:  https://youtu.be/XX63uoILXRI and https://youtu.be/cht971-WvT8 on Youtube, where you can clearly see how the cluster processor controls the motors:
1. When power is on, the needles of all gauges start move to zero;
2. The needle that first gets mechanical zero - stops. Does not click, does not twitch. Just stop.
3. After the last of the needles gets its mechanical zero - calibration is complete.

It is also worth mentioning that on the cluster PCB the motors are connected directly to the processor, there are no position sensors.

Please tell me what you think about this? How can this work? Thanks in advance!

**Comment by guyc** [comment]
Nice pics and video.  I think there is a lot of room for improvement with the noise from this code; I wish I had an excuse to dedicate some time to experimentation.

The best advice I can offer on silent power-on resets is to study this document: https://guy.carpenter.id.au/gaugette/resources/vid/2009111395111_Acceleration_&_reset_calculation_example.pdf
which gives advice on customsing the acceleration table for quiet resets.  You could easily modify this code to use different acceleration tables for reset and normal operation.

I've never seen anyone trying to sense motor stop by e.g. measuring current flow through the drive pins, although I've read this is possible with DC motors.  (e.g. https://forum.arduino.cc/t/easy-way-to-determine-if-a-motor-has-stopped/157502)  It would be a very interesting experiment to try.  My suspicion from observing auto and motorcycle instruments is that they do not do this; they just quietly push against the stop.

**Comment by SamFisher015** [comment]
Thank you for your quick answer!

In the second video I stopped the needle by my finger and the motor stopped. At the same time the second one continued its movement until it reached a mechanical stop inside the motor.

I think that if the motor had been rotating counterclockwise for the full number of steps (even at a slow speed), it should have continued moving after I removed my finger. But I still assume that the car cluster processor somehow determined that there was an obstruction in the needle's path.

I bought a logic analyzer and want to learn more about the signals to the motor contact during "working" movement and movement during "zeroing". I assume that there should be some difference and maybe an answer.

When I learn the difference in control signals, I will write in this thread, maybe it will give some result.

**Comment by SamFisher015** [comment]
Hello! I connected my new logic analyzer to the dashboard motor and made measurements in the return to zero mode, as well as in the operating mode, sending a speed signal of 200 km/h to the dashboard. In addition, I connected the logic analyzer directly to the motor controlled by the Arduino Nano using your library.

The results were predictable. In all three cases, the motor control signal was different. I suggest you look at the graphs. The resolution on all three graphics is the same 100 px = 2 ms.

![Возврат в 0](https://github.com/user-attachments/assets/65c18a76-6f11-4e5c-9d8c-6a5c6df4e47e)
![От 0 до 200 кмч](https://github.com/user-attachments/assets/77caea79-e9bf-4b39-a135-e178844d6151)
![От 0 до 600 шагов с библиотекой SwitecX25](https://github.com/user-attachments/assets/6e02fd70-ecf6-40f5-aade-7a0dc4e2251e)

It is obvious that the dashboard developers have provided a more complicated algorithm for controlling the stepper motors. That is why the arrow movement is so smooth, without jerks.

It seems to me that a PWM signal with a frequency of 15.6 kHz is used here, judging by the measurements. And the control sequence for the motor outputs is completely different.

Also, the graphs clearly show the moment when the needle rests against the mechanical stop, which means the theory that the microcontroller understands the moment of the physical stop of the arrow is correct.

![Момент упора в ноль](https://github.com/user-attachments/assets/6dabbc71-ac25-4a75-9ebc-564454c8bc21)

The only thing left to do is to write a motor control library with the same operating principle! 😄 😄 😄 (But I have no ideas on how to do this yet.😥) Maybe you will have some thoughts on this matter?...

**Comment by guyc** [comment]
@SamFisher015 there is quite a bit to digest there.  Thanks for including such nice data.

Regarding PWM, this library supports microstepping via PWM only if using a driver chip like the X12 quad driver. (https://guy.carpenter.id.au/gaugette/2017/04/29/switecx25-quad-driver-tests/) which gives much smoother motion.

One very obvious characteristic of the X25 step pattern is that contacts 2 and 3 are common.  Even with microstepping I would expect that pattern to be visible, and it isn't for your motor.  Do you have any reference documentation for your motor?
![image](https://github.com/user-attachments/assets/9d0cd9e0-faee-472c-80df-c7c01753d827)

The zeroing behaviour is really interesting, I'm still puzzling over that pattern.

I've been contemplating using something like an RP2040 to do microstepping without a dedicated driver chip.  I hadn't considered stop detection as a possibility before this thread, but now I'm really curious about the possibility.

**Comment by SamFisher015** [comment]
Hello!

I recently spoke with ChatGPT about this issue, and he insists that you need to use PWM with sine and cosine calculations. This way, you can rotate the motor smoothly, without the jerking and audible rustling that occurs with discrete step control.

<img width="361" height="51" alt="Image" src="https://github.com/user-attachments/assets/a4495c69-c807-4a7b-9a38-1ea0e25050a0" />

1. Determine the needle angle (0–360°).
2. Calculate the sine and cosine: I_A = sin(angle), I_B = cos(angle)
3. Convert to PWM (0–255) and feed it to the MOSFET.
4. Repeat with small angle increments → the needle moves smoothly.

The main idea: PWM doesn't directly move the motor; it controls the current in the coils. The motor automatically turns in the direction of the magnetic field created.
